# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/get_free_slot
Accept: application/json

###

POST http://127.0.0.1:8000/change_slot_busy/3
Accept: application/json